var sols = [
	"Final Fantasy X",
	"Metal Gear Solid 3",
	"Persona 4",
	"Metal Gear Solid 2",
	"Dofus",
	"Skyward Sword",
	"Rust",
	"Dissidia NT",
	"Fire Emblem Heroes",
	"Kid Icarus Uprising",
	"Clash Royale",
	"Baten Kaitos",
	"Osu!",
	"Persona 5: Dancing Star Night",
	"Persona 4: Dancing all Night",
	"Soul Calibur 2",
	"Tekken x Street Fighter",
	"Okami",
	"Ultimate Marvel vs Capcom 3",
	"Persona 4: Arena",
	"Tony Hawk's Pro Skater 2",
	"Metal Gear Solid V",
	"Kingdom Hears 3D",
	"Super Smash Bros Brawl",
	"Osu Tatakae Ouendan 2",
	"Breath of the Wild",
	"Death Stranding",
	"Stanley Parable",
	"Mario Party 4",
	"Final Fantasy VII",
	"Street Fighter II",
	"Call of duty Black Ops 2",
	"Conker's bad fur day",
	"Metroid prime",
	"Halo 2",
	"Shadow of the Colossus",
	"Wii Fit",
	"Golden Sun 2",
	"Bravely Default",
	"Tales of Phantasia",
	"Dragon Ball Adventure",
	"Fire Emblem Echoes",
	"Monster Hunter 4 Ultimate",
	"Ace Attorney: Dual Destinies",
	"Pokemon X/Y",
	"Virtue's Last Reward",
	"Pokemon Crystal",
	"Fire Emblem: Path of Radiance",
	"Mario Kart: Double Dash",
	"Link's Awakening",
	"Metroid Prime 2",
	"Metroid Prime 3",
	"Metroid Federation Forces",
	"Metroid Prime Hunters",
	"Persona 5",
	"Mario Power Tennis GBA",
	"Ace Attorney: Apollo Justice",
	"Ace Attorney: Spirit of Justice",
	"Pokemon OR/AS",
	"Pokemon Sun/Moon",
	"Pokemon Ultra Sun/Moon",
	"Xenoblade Chronicles",
	"Xenoblade Chronicles X",
	"Persona 3",
	"Persona 3 Portable",
	"Touhou 12",
	"Fire Embem: Geneology of Holy War",
	"Fire Emblem: Sword of Seals",
	"Fire Emblem: Radiant Dawn",
	"Advance Wars",
	"Dragon Ball Xenoverse 2",
	"Pikmin",
	"Smash Bros 4 3DS",
	"AC: Happy Home Designer",
	"Dr Luigi",
	"Earthbound",
	"Luigi's Mansion 2",
	"Luigi's Mansion",
	"NintendoLand",
	"Pikmin 2",
	"Pikmin 3",
	"Smash Bros 4 WiiU",
	"Banjo Tooie",
	"Bioshock",
	"Danganronpa",
	"Cuphead",
	"Ultra Despair Girls",
	"Danganronpa V3",
	"Hatoful Boyfriend",
	"A Dad Dating Simulator",
	"Hey you, Pikachu!",
	"Majora's Mask",
	"Limbo",
	"Owlboy",
	"Ocarina of Time",
	"Yooka Laylee",
	"Super Mario Maker",
	"Ori and the blind forest",
	"One Thousand Lies",
	"Sonic Forces",
	"Xenoblade Chronicles 2",
	"Second Life",
	"Tony Hawk's Pro Skater",
	"Metal Gear Solid",
	"Shrek Game Boy",
	"Shenmue",
	"Parappa the Rapper",
	"WarioWare: Smooth Moves",
	"Metroid",
	"Grush",
	"A Hat in Time",
	"Enter the Gungeon",
	"Civilization VI",
	"Shovel Knight",
	"Garry's Mod",
	"Portal 2",
	"Overwatch",
	"Sonic Generations",
	"Sonic Adventure 2",
	"Ratchet and Clank: Tools of Destruction",
	"Spyro 2",
	"Portal",
	"Kingdom Hearts",
	"Castle Crashers",
	"Phoenix Wright: Ace Attorney",
	"Touhou 8",
	"Final Fantasy VIII",
	"Sonic R",
	"Binding of Isaac",
	"Undertale",
	"A Link to the Past",
	"Pokemon Yellow",
	"Final Fantasy IX",
	"Danganronpa 2",
	"Bastion",
	"Bravely Default",
	"Child of Light",
	"Final Fantasy: Crystal Chronicles",
	"Donkey Kong 64",
	"Diddy Kong Racing",
	"Kingdom Hearts 258/2",
	"Smash Bros Melee",
	"Mickey Mania",
	"Pokemon GO",
	"Sushi Striker",
	"Twilight Princess",
	"Dark Souls",
	"Golden Sun 2",
	"Ib",
	"Yugioh Forbidden Memories",
	"Devil Daggers",
	"Digimon Rumble Arena",
	"Earthworm Jim",
	"Lost Magic",
	"LSD Dream Emulator",
	"Spec Ops: The Line",
	"Pandora's Tower",
	"Talmit's adventure",
	"Kula World",
	"The Blue Brothers",
	"Bomberman Generation",
	"Dragon's Lair",
	"Final Fantasy Tactics",
	"The Witch's House",
	"Hamtaro Ham Ham Games",
	"Final Fantasy: Echoes of Time",
	"Shining Force",
	"Another Code R",
	"Final Fantasy 12: Revenant Wings",
	"Frogger",
	"Bubble Bobble",
	"Advance Wars: Dark Conflict",
	"Borderlands 2",
	"Civilization VI",
	"Doom",
	"Sacred",
	"Mirror's Edge",
	"Dark souls 3",
	"The witcher 3: Wild hunt",
	"Team Fortress 2",
	"Half life 2",
	"Fallout 4",
	"Mass Effect 3",
	"GTA Vice City",
	"Animal Crossing",
	"Battalion Wars",
	"Fire Emblem 7",
	"Pokemon Esmeralda",
	"Pokemon Channel",
	"Minish Cap",
	"Pokemon Heart Gold",
	"Wind Waker",
	"Pokemon: Trading Card Game",
	"Steins Gate",
	"Mario Party 2",
	"Pokemon Stadium",
	"Pokemon Snap",
];
