//---------------------------------------------------------------------------------------
//--------------------------------- AUTOCOMPLETE DATABASE -------------------------------
//---------------------------------------------------------------------------------------

var atlus_sols = [
	"Persona 4",
	"Persona Q",
	"Persona 5",
	"Persona 4 Arena",
	"Persona 3",
	"Catherine",
	"Etrian odyssey 4",
	"Persona 4 Dancing All Night",
];

var anime_sols = [
	"Haikyuu!",
	"Kuroko no Basket",
	"Clannad After Story",
	"Your Name",
	"Shingeki no Kyojin",
	"Katekyo Hitman Reborn!",
	"Full Metal Alchemist: Brotherhood",
	"Kill la Kill",
	"Boku no Hero Academia",
	"Bleach",
	"Death Parade",
	"The Melancholy of Haruhi Suzumiya",
	"Mirai Nikki",
	"Sword Art Online",
	"Sword Art Online 2",
	"One Piece",
	"No Game no Life",
	"Fairy Tail",
	"Code Geass",
	"Death Note",
	"Parasyte",
	"Clannad",
	"Puella Magi Madoka Magica",
	"Guilty Crown",
	"Steins;Gate",
	"Tokyo Ghoul",
	"Dragon Ball Z",
	"Another",
	"Digimon",
	"Digimon Adventure Tri",
	"Hajime no Ippo",
	"High School of the Death",
	"Lucky Star",
	"Naruto Shippuden",
	"Shigatsu Wa Kimi no Uso",
	"Tengen Toppa Gurren Lagann",
	"Ping Pong The Animation",
	"Baka to Test to Shoukanjuu",
];
	
var remix_sols = [
	"Undertale",
	"Touhou 10",
	"Super Mario RPG",
	"Final Fantasy IX",
	"Ducktales",
	"Kingdom Hearts",
	"Megaman 2",
	"Final Fantasy VIII",
	"Final Fantasy VII",
	"Final Fantasy X",
	"The Legend of Zelda: Ocarina of Time",
	"Super Mario World",
	"Pokemon Red",
	"Pokemon Blue",
	"Pokemon Yellow",
	"Donkey Kong 64",
	"Touhou 8",
	"Touhou 4",
	"Persona 5",
	"Touhou 6",
];
	
var touhou_sols = [
	"Touhou 4",
	"Touhou 6",
	"Touhou 7",
	"Touhou 7.5",
	"Touhou 8",
	"Touhou 9",
	"Touhou 10",
	"Touhou 10.5",
	"Touhou 11",
	"Touhou 12",
	"Touhou 12.3",
	"Touhou 12.8",
];
	
var mario_sols = [
	"Super Mario Odyssey",
	"Super Mario Sunshine",
	"Super Mario Bros 3",
	"Super Mario Galaxy",
	"Super Mario Galaxy 2",
	"Super Mario Bros 2",
];
	
var kirby_sols = [
	"Kirby's Return to dreamland",
	"Kirby Triple Deluxe",
	"Kirby's Dreamland",
	"Kirby Superstar",
	"Kirby 64",
];
	
var pokemon_sols = [
	"Pokemon Omega Ruby",
	"Pokemoon Alpha Sapphire",
	"Pokemon Sun",
	"Pokemon Moon",
	"Pokemon X",
	"Pokemon Y",
	"Pokemon Black",
	"Pokemon White",
	"Pokemon Diamond",
	"Pokemon Pearl",
	"Pokemon Heart Gold",
	"Pokemon Soul Silver",
	"Pokemon Fire Red",
	"Pokemon Leaf Green",
	"Pokemon Black 2",
	"Pokemon White 2",
	"Pokemon Red",
	"Pokemon Blue",
	"Pokemon Yellow",
	"Pokemon Ruby",
	"Pokemon Sapphire",
	"Pokemon Emerald",
	"Pokemon Colosseum",
];

var square_sols = [
	"Kingdom Hearts 2.8",
	"Final Fantasy VII",
	"Final Fantasy VIII",
	"Final Fantasy IX",
	"Final Fantasy X",
	"Final Fantasy XIII",
	"Kingdom Hearts",
	"Bravely Second: End Layer",
	"Bravely Default: Flying Fairy",
	"Final Fantasy IV",
	"Final Fantasy V",
	"Final Fantasy III",
	"Final Fantasy VI",
	"Final Fantasy I",
];

var sonic_sols = [
	"Sonic 2006",
	"Sonic Generations",
	"Sonic Adventure 2",
	"Sonic Colors",
	"Sonic The Hedgehog 3 & Knuckles",
	"Sonic The Hedgehog",
	"Sonic Heroes",
	"Sonic Unleashed",
	"Sonic and The Black Knight",
];

var spikechun_sols = [
	"Nine Hours, Nine Persons, Nine Doors",
	"Virtue's Last Reward",
	"Zero Time Dilema",
	"Danganronpa",
	"Danganronpa 2",
	"Danganronpa Ultra Despair Girls",
];

var k3_sols = [
	"One piece",
	"Detective Conan",
	"Corrector Yui",
	"Dragon Ball Z",
	"Bob the Builder",
	"Bobobo-bo Bo-bobo",
	"New Dr Slump",
	"Dragon Ball",
	"Doraemon",
	"Fruits Basket",
	"Fushigi Yugi",
	"Ninja Hattori",
	"Inuyasha",
	"Kamikaze Kaitou Jeanne",
	"Keroro",
	"Kimagure Orange Road",
	"Kiteretsu",
	"Kochikame",
	"The Law of Ueki",
	"Love Hina",
	"Ojamajo Doremi",
	"Yuyu Hakusho",
	"Slam Dunk",
	"Shin Chan",
	"Code Lyoko",
	"CatDog",
	"Galactik Football",
	"Card Captor Sakura",
	"Tsubasa Reservoir Chronicle",
	"Sailor Moon",
	"Ninja Boy Rantaro",
	"DNA2",
	"Cowboy Bebop",
];

var zelda_sols = [
	"The Legend of Zelda: A Link Between Worlds",
	"The Legend of Zelda: Ocarina of time",
	"The Legend of Zelda: Wind Waker",
	"The Legend of Zelda: Spirit Tracks",
	"The Legend of Zelda: Breath of the Wild",
	"The Legend of Zelda: Phantom Hourglass",
	"The Legend of Zelda: Majora's Mask",
	"The Legend of Zelda: Skyward Sword",
	"The Legend of Zelda: Twilight Princess",
	"The Legend of Zelda: Link's Awakening",
];
	
var attorney_sols = [
	"Ace Attorney Investigations: Miles Edgeworth",
	"Apollo Justice: Ace Attorney",
	"Phoenix Wright: Ace Attorney: Dual Destinies",
	"Ace Attorney Investigations 2",
	"Phoenix Wright: Ace Attorney",
	"Phoenix Wright: Ace Attorney: Spirit of Justice",
	"Phoenix Wright: Ace Attorney: Trials and Tribulations",
	"Professor Layton vs. Phoenix Wright: Ace Attorney",
	"Phoenix Wright: Ace Attorney: Justice for All",
];

var disney_sols = [
	"The Little Mermaid",
	"The Lion King",
	"Aladdin",
	"Tangled",
	"Mulan",
	"Hercules",
	"Tarzan",
	"Toy Story",
	"Snow White",
	"Mary Poppins",
	"Phineas and Ferb",
	"Hannah Montana",
	"Wizards of Waverly Place",
	"Camp Rock",
	"The Nightmare before Christmas",
	"Lilo & Stitch",
	"Frozen",
	"High School Musical",
	"High School Musical 2",
	"Kim possible",
	"Beauty and the Beast",
	"The Jungle Book",
	"Moana",
	"Zootopia",
	"Jhonny Test",
	"Monster Inc",
	"Oliver and Company",
	"The Hunchback of Notre Dame",
	"Anastasia",
	"The Lion King 2",
	"Pocahontas",
	"Princess and the frog",
];
	